#!/usr/bin/bash



var=$(hostname -s); echo $var
echo "***** hostname is ${var} *****"
echo Your username variable is \$USER.



###for loop
for VARIABLE in LIST; do
COMMAND VARIABLE
done


for HOST in host1 host2 host3;
do echo $HOST;
done

option -> host{1,2,3} -> host{1..5} -> host{a..g}




transport=('car' 'train' 'bike' 'bus')
echo "${transport[@]}"

# $1 = read the first argument, number can be changed 
# @ = show all elements in array


