#!/usr/bin/bash



var=$(hostname -s); echo $var
echo "***** hostname is ${var} *****"
echo Your username variable is \$USER.





###for loop
for VARIABLE in LIST; do
COMMAND VARIABLE
done

for HOST in host1 host2 host3;
do echo $HOST;
done

option -> host{1,2,3} -> host{1..5} -> host{a..g}

seq 2 2 10 = start2 +2 end10
seq 10 -1 1

exit 2 = exit code check with "echo $?"

gt = greater than
ge = greater than equal 
lt = less than
le = less than equal 

z = zero length 
n = non-zero length 
-f = file
-d = dictionary 
-L = symbolic link
-R = read permission 



transport=('car' 'train' 'bike' 'bus')
echo "${transport[@]}"

# $1 = read the first argument, number can be changed 
# @ = show all elements in array


