#!/usr/bin/bash



var=$(hostname -s); echo $var
echo "***** hostname is ${var} *****"
echo Your username variable is \$USER.



for VARIABLE in LIST; do
COMMAND VARIABLE
done


transport=('car' 'train' 'bike' 'bus')
echo "${transport[@]}"

# $1 = read the first argument, number can be changed 
# @ = show all elements in array


